/**
 * Refresh admin1 + Mexico fill lists for community_14_nations globe geometry.
 * Merges intersections from ne_110m admin_1 (US) + ne_50m admin_1 (CA + others).
 *
 * pnpm -C frontend exec tsx scripts/buildCommunity14nAdmin1Map.ts
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import bboxPolygon from '@turf/bbox-polygon';
import booleanIntersects from '@turf/boolean-intersects';
import type { Feature, FeatureCollection, MultiPolygon, Polygon } from 'geojson';

const NE110 =
  'https://cdn.jsdelivr.net/gh/nvkelso/natural-earth-vector@master/geojson/ne_110m_admin_1_states_provinces.geojson';
const NE50 =
  'https://cdn.jsdelivr.net/gh/nvkelso/natural-earth-vector@master/geojson/ne_50m_admin_1_states_provinces.geojson';

const RAW: { id: string; w: number; s: number; e: number; n: number }[] = [
  { id: 'na_dene', w: -145, s: 55, e: -112, n: 65 },
  { id: 'na_cree', w: -112, s: 55, e: -80, n: 65 },
  { id: 'na_innu', w: -80, s: 55, e: -55, n: 65 },
  { id: 'na_tlingit', w: -145, s: 49, e: -130, n: 55 },
  { id: 'na_salish', w: -130, s: 49, e: -122, n: 55 },
  { id: 'na_blackfoot', w: -122, s: 49, e: -110, n: 55 },
  { id: 'na_assiniboine', w: -110, s: 49, e: -100, n: 55 },
  { id: 'na_ojibwe', w: -100, s: 49, e: -88, n: 55 },
  { id: 'na_algonquin', w: -88, s: 49, e: -72, n: 55 },
  { id: 'na_mikmaq', w: -72, s: 49, e: -55, n: 55 },
  { id: 'na_chinook', w: -130, s: 44, e: -122, n: 49 },
  { id: 'na_yakama', w: -122, s: 44, e: -115, n: 49 },
  { id: 'na_crow', w: -115, s: 44, e: -105, n: 49 },
  { id: 'na_lakota', w: -105, s: 44, e: -96, n: 49 },
  { id: 'na_potawatomi', w: -96, s: 44, e: -86, n: 49 },
  { id: 'na_haudenosaunee', w: -86, s: 44, e: -76, n: 49 },
  { id: 'na_wabanaki', w: -76, s: 44, e: -66, n: 49 },
  { id: 'na_kalapuya', w: -126, s: 40, e: -121, n: 44 },
  { id: 'na_great_basin', w: -121, s: 39, e: -112, n: 44 },
  { id: 'na_pawnee', w: -112, s: 39, e: -103, n: 44 },
  { id: 'na_osage', w: -103, s: 39, e: -96, n: 44 },
  { id: 'na_shawnee', w: -96, s: 39, e: -86, n: 44 },
  { id: 'na_powhatan', w: -86, s: 39, e: -76, n: 44 },
  { id: 'na_pomo', w: -125, s: 36, e: -121, n: 40 },
  { id: 'na_chumash', w: -121, s: 31, e: -115, n: 39 },
  { id: 'na_dine', w: -115, s: 34, e: -108, n: 39 },
  { id: 'na_pueblo', w: -108, s: 33, e: -103, n: 39 },
  { id: 'na_comanche', w: -103, s: 33, e: -96, n: 39 },
  { id: 'na_caddo', w: -96, s: 33, e: -91, n: 39 },
  { id: 'na_cherokee', w: -91, s: 33, e: -83, n: 39 },
  { id: 'na_tuscarora', w: -83, s: 33, e: -76, n: 39 },
  { id: 'na_yavapai', w: -115, s: 27, e: -108, n: 34 },
  { id: 'na_apache', w: -108, s: 27, e: -103, n: 33 },
  { id: 'na_jumano', w: -103, s: 27, e: -96, n: 33 },
  { id: 'na_chickasaw', w: -96, s: 27, e: -90, n: 33 },
  { id: 'na_muscogee', w: -90, s: 27, e: -84, n: 33 },
  { id: 'na_florida', w: -84, s: 24, e: -79, n: 33 },
  { id: 'na_tohono', w: -115, s: 21, e: -107, n: 27 },
  { id: 'na_coahuiltecos', w: -107, s: 21, e: -98, n: 27 },
  { id: 'na_huastec', w: -98, s: 21, e: -90, n: 27 },
  { id: 'na_purepecha', w: -107, s: 15, e: -100, n: 21 },
  { id: 'na_mexica', w: -100, s: 15, e: -94, n: 21 },
  { id: 'na_maya', w: -94, s: 15, e: -86, n: 21 },
];

function codesFor(
  geo: FeatureCollection<Polygon | MultiPolygon>,
  bbox: [number, number, number, number],
): string[] {
  const bp = bboxPolygon(bbox);
  const c = new Set<string>();
  for (const f of geo.features) {
    const iso = (f.properties as Record<string, unknown>)?.['iso_3166_2'];
    if (typeof iso !== 'string') continue;
    try {
      if (booleanIntersects(f as Feature<Polygon | MultiPolygon>, bp)) c.add(iso);
    } catch {
      /* skip */
    }
  }
  return [...c].sort();
}

/** Maritime & Mexico: NE50 bbox tests miss islands; clip full provinces + MX country */
const MANUAL_ADMIN1: Record<string, string[]> = {
  /** Islands / ME peninsula: bbox intersection misses NE admin-1 */
  na_mikmaq: ['CA-NB', 'CA-NS', 'CA-PE', 'US-ME', 'US-NH'],
};

/** Solely or primarily Mexico — admin-0 clip */
const FILL_MX: Set<string> = new Set([
  'na_tohono',
  'na_purepecha',
  'na_mexica',
  'na_maya',
]);

/** US–Mexico border strips: union US admin-1 + clipped Mexico */
const ALSO_FILL_MX: Set<string> = new Set(['na_coahuiltecos', 'na_huastec']);

async function main() {
  const [r110, r50] = await Promise.all([fetch(NE110), fetch(NE50)]);
  const geo110 = (await r110.json()) as FeatureCollection<Polygon | MultiPolygon>;
  const geo50 = (await r50.json()) as FeatureCollection<Polygon | MultiPolygon>;

  const lines: string[] = [
    '/**',
    ' * "The 14 Nations" — globe geometry from Natural Earth (same principle as Risorgimento / era maps):',
    ' * union admin-1 regions (US: ne_110m, Canada: ne_50m), optional Mexico (admin-0 clip), then clip to territory bbox.',
    ' *',
    ' * Generated by: pnpm -C frontend exec tsx scripts/buildCommunity14nAdmin1Map.ts',
    ' */',
    '',
    "import type { ClipBbox } from './territoryGeoMapping';",
    '',
    'export interface Community14nTerritoryGeoDef {',
    '  admin1: string[];',
    '  clip_bbox: ClipBbox;',
    "  /** Clip entire country polygon (admin-0) when admin-1 not in Natural Earth (e.g. Mexico). */",
    '  fill_country_iso?: "MX";',
    '}',
    '',
    'export const COMMUNITY_14N_TERRITORY_GEO: Record<string, Community14nTerritoryGeoDef> = {',
  ];

  for (const r of RAW) {
    const bbox: [number, number, number, number] = [r.w, r.s, r.e, r.n];
    const merged = new Set([...codesFor(geo110, bbox), ...codesFor(geo50, bbox)]);
    for (const x of MANUAL_ADMIN1[r.id] ?? []) merged.add(x);

    let admin1 = [...merged].sort();
    let fillMx = FILL_MX.has(r.id) || ALSO_FILL_MX.has(r.id);

    if (FILL_MX.has(r.id)) {
      admin1 = admin1.filter((c) => !c.startsWith('MX-'));
    }

    if (admin1.length === 0 && !fillMx) {
      console.warn(`WARN: ${r.id} empty — using MX fill if south, else check manually`);
      if (r.s < 28) fillMx = true;
    }

    const fillStr = fillMx ? ', fill_country_iso: "MX"' : '';
    lines.push(
      `  ${JSON.stringify(r.id)}: { admin1: ${JSON.stringify(admin1)}, clip_bbox: [${r.w}, ${r.s}, ${r.e}, ${r.n}]${fillStr} },`,
    );
  }

  lines.push('};', '');
  lines.push(
    'export function isCommunity14nTerritory(territoryId: string): boolean {',
    '  return territoryId.startsWith("na_") && territoryId in COMMUNITY_14N_TERRITORY_GEO;',
    '}',
    '',
  );

  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const out = path.join(__dirname, '../src/data/community14nAdmin1Map.ts');
  fs.writeFileSync(out, lines.join('\n'), 'utf8');
  console.log('Wrote', out);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
