/**
 * "The 14 Nations" — globe geometry from Natural Earth (same principle as Risorgimento / era maps):
 * union admin-1 regions (US: ne_110m, Canada: ne_50m), optional Mexico (admin-0 clip), then clip to territory bbox.
 *
 * Generated by: pnpm -C frontend exec tsx scripts/buildCommunity14nAdmin1Map.ts
 */

import type { ClipBbox } from './territoryGeoMapping';

export interface Community14nTerritoryGeoDef {
  admin1: string[];
  clip_bbox: ClipBbox;
  /** Clip entire country polygon (admin-0) when admin-1 not in Natural Earth (e.g. Mexico). */
  fill_country_iso?: "MX";
}

export const COMMUNITY_14N_TERRITORY_GEO: Record<string, Community14nTerritoryGeoDef> = {
  "na_dene": { admin1: ["CA-AB","CA-BC","CA-NT","CA-YT","US-AK"], clip_bbox: [-145, 55, -112, 65] },
  "na_cree": { admin1: ["CA-AB","CA-MB","CA-NT","CA-NU","CA-ON","CA-SK"], clip_bbox: [-112, 55, -80, 65] },
  "na_innu": { admin1: ["CA-NL","CA-NU","CA-QC"], clip_bbox: [-80, 55, -55, 65] },
  "na_tlingit": { admin1: ["CA-BC","US-AK"], clip_bbox: [-145, 49, -130, 55] },
  "na_salish": { admin1: ["CA-BC","US-WA"], clip_bbox: [-130, 49, -122, 55] },
  "na_blackfoot": { admin1: ["CA-AB","CA-BC","US-ID","US-MT","US-WA"], clip_bbox: [-122, 49, -110, 55] },
  "na_assiniboine": { admin1: ["CA-AB","CA-MB","CA-SK","US-MT","US-ND"], clip_bbox: [-110, 49, -100, 55] },
  "na_ojibwe": { admin1: ["CA-MB","CA-ON","US-MN","US-ND"], clip_bbox: [-100, 49, -88, 55] },
  "na_algonquin": { admin1: ["CA-NU","CA-ON","CA-QC"], clip_bbox: [-88, 49, -72, 55] },
  "na_mikmaq": { admin1: ["CA-NB","CA-NL","CA-NS","CA-PE","CA-QC","US-ME","US-NH"], clip_bbox: [-72, 49, -55, 55] },
  "na_chinook": { admin1: ["CA-BC","US-OR","US-WA"], clip_bbox: [-130, 44, -122, 49] },
  "na_yakama": { admin1: ["CA-BC","US-ID","US-MT","US-OR","US-WA"], clip_bbox: [-122, 44, -115, 49] },
  "na_crow": { admin1: ["CA-AB","CA-BC","CA-SK","US-ID","US-MT","US-WY"], clip_bbox: [-115, 44, -105, 49] },
  "na_lakota": { admin1: ["CA-MB","CA-SK","US-MN","US-MT","US-ND","US-SD","US-WY"], clip_bbox: [-105, 44, -96, 49] },
  "na_potawatomi": { admin1: ["CA-MB","CA-ON","US-MI","US-MN","US-WI"], clip_bbox: [-96, 44, -86, 49] },
  "na_haudenosaunee": { admin1: ["CA-ON","CA-QC","US-MI","US-NY"], clip_bbox: [-86, 44, -76, 49] },
  "na_wabanaki": { admin1: ["CA-NB","CA-NS","CA-ON","CA-QC","US-ME","US-NH","US-NY","US-VT"], clip_bbox: [-76, 44, -66, 49] },
  "na_kalapuya": { admin1: ["US-CA","US-OR"], clip_bbox: [-126, 40, -121, 44] },
  "na_great_basin": { admin1: ["US-CA","US-ID","US-NV","US-OR","US-UT"], clip_bbox: [-121, 39, -112, 44] },
  "na_pawnee": { admin1: ["US-CO","US-ID","US-NE","US-SD","US-UT","US-WY"], clip_bbox: [-112, 39, -103, 44] },
  "na_osage": { admin1: ["US-CO","US-IA","US-KS","US-MN","US-NE","US-SD"], clip_bbox: [-103, 39, -96, 44] },
  "na_shawnee": { admin1: ["US-IA","US-IL","US-IN","US-KS","US-MI","US-MN","US-MO","US-NE","US-WI"], clip_bbox: [-96, 39, -86, 44] },
  "na_powhatan": { admin1: ["CA-ON","US-DC","US-IN","US-KY","US-MD","US-MI","US-NY","US-OH","US-PA","US-VA","US-WV"], clip_bbox: [-86, 39, -76, 44] },
  "na_pomo": { admin1: ["US-CA"], clip_bbox: [-125, 36, -121, 40] },
  "na_chumash": { admin1: ["US-CA","US-NV"], clip_bbox: [-121, 31, -115, 39] },
  "na_dine": { admin1: ["US-AZ","US-CA","US-CO","US-NM","US-NV","US-UT"], clip_bbox: [-115, 34, -108, 39] },
  "na_pueblo": { admin1: ["US-CO","US-NM","US-OK","US-TX"], clip_bbox: [-108, 33, -103, 39] },
  "na_comanche": { admin1: ["US-CO","US-KS","US-OK","US-TX"], clip_bbox: [-103, 33, -96, 39] },
  "na_caddo": { admin1: ["US-AR","US-KS","US-LA","US-MO","US-MS","US-OK","US-TX"], clip_bbox: [-96, 33, -91, 39] },
  "na_cherokee": { admin1: ["US-AL","US-AR","US-GA","US-IL","US-IN","US-KY","US-MO","US-MS","US-NC","US-OH","US-SC","US-TN","US-VA"], clip_bbox: [-91, 33, -83, 39] },
  "na_tuscarora": { admin1: ["US-DC","US-GA","US-KY","US-MD","US-NC","US-OH","US-SC","US-TN","US-VA","US-WV"], clip_bbox: [-83, 33, -76, 39] },
  "na_yavapai": { admin1: ["US-AZ","US-CA","US-NM"], clip_bbox: [-115, 27, -108, 34] },
  "na_apache": { admin1: ["US-NM","US-TX"], clip_bbox: [-108, 27, -103, 33] },
  "na_jumano": { admin1: ["US-TX"], clip_bbox: [-103, 27, -96, 33] },
  "na_chickasaw": { admin1: ["US-LA","US-MS","US-TX"], clip_bbox: [-96, 27, -90, 33] },
  "na_muscogee": { admin1: ["US-AL","US-FL","US-GA","US-LA","US-MS"], clip_bbox: [-90, 27, -84, 33] },
  "na_florida": { admin1: ["US-FL","US-GA","US-SC"], clip_bbox: [-84, 24, -79, 33] },
  "na_tohono": { admin1: [], clip_bbox: [-115, 21, -107, 27], fill_country_iso: "MX" },
  "na_coahuiltecos": { admin1: ["US-TX"], clip_bbox: [-107, 21, -98, 27], fill_country_iso: "MX" },
  "na_huastec": { admin1: ["US-TX"], clip_bbox: [-98, 21, -90, 27], fill_country_iso: "MX" },
  "na_purepecha": { admin1: [], clip_bbox: [-107, 15, -100, 21], fill_country_iso: "MX" },
  "na_mexica": { admin1: [], clip_bbox: [-100, 15, -94, 21], fill_country_iso: "MX" },
  "na_maya": { admin1: [], clip_bbox: [-94, 15, -86, 21], fill_country_iso: "MX" },
};

export function isCommunity14nTerritory(territoryId: string): boolean {
  return territoryId.startsWith("na_") && territoryId in COMMUNITY_14N_TERRITORY_GEO;
}
