import type { Faction, TechNode } from './types';

// ── Factions ──────────────────────────────────────────────────────────────────
export const ANCIENT_FACTIONS: Faction[] = [
  {
    faction_id: 'rome',
    name: 'Roman Republic',
    description: 'Disciplined legions re-roll their lowest attack die and receive extra reinforcements from Italic territory.',
    home_region_ids: ['roman_west'],
    passive_attack_bonus: 0,   // legion_reroll is an era-wide modifier; rome gets reinforce bonus on top
    reinforce_bonus: 1,
    ability_id: 'testudo',
    ability_description: 'Testudo Formation: once per turn during attack phase, negate all attacker losses on one combat exchange.',
    color: '#c0392b',
  },
  {
    faction_id: 'parthia',
    name: 'Parthian Empire',
    description: 'Mounted archers force attackers into the attack phase with one fewer attack die when assaulting Parthian territories.',
    home_region_ids: ['parthia'],
    passive_defense_bonus: 1,
    ability_id: 'parting_shot',
    ability_description: 'Parting Shot: after losing a territory, immediately deal 1 unit loss to the attacker.',
    color: '#8e44ad',
  },
  {
    faction_id: 'han',
    name: 'Han Dynasty',
    description: 'Vast territory and organized bureaucracy generates +2 extra reinforcements per turn.',
    home_region_ids: ['han_china'],
    reinforce_bonus: 2,
    ability_id: 'silk_road',
    ability_description: 'Silk Road: once per turn during draft, add +3 tech points.',
    color: '#e67e22',
  },
  {
    faction_id: 'maurya',
    name: 'Maurya Empire',
    description: 'War elephants add +1 attack die when assaulting territories with 3 or fewer defenders.',
    home_region_ids: ['india'],
    passive_attack_bonus: 1,
    ability_id: 'war_elephants',
    ability_description: 'War Elephants: once per turn, one attack roll uses 4 dice (max).',
    color: '#27ae60',
  },
  {
    faction_id: 'carthage',
    name: 'Carthaginian Republic',
    description: 'Naval supremacy allows sea-lane fortify moves at no extra cost and +1 defense on coastal territories.',
    home_region_ids: ['africa'],
    passive_defense_bonus: 1,
    ability_id: 'naval_supremacy_ancient',
    ability_description: 'Naval Supremacy: move units along sea connections without restriction during fortify phase.',
    color: '#2980b9',
  },
  {
    faction_id: 'germanic_tribes',
    name: 'Germanic Tribes',
    description: 'Fierce forest fighters — +1 defense die on all defense rolls.',
    home_region_ids: ['germanic', 'steppe'],
    passive_defense_bonus: 1,
    reinforce_bonus: 0,
    ability_id: 'ambush',
    ability_description: 'Ambush: once per turn, attack from a border territory using 1 extra die.',
    color: '#7f8c8d',
  },
];

// ── Tech Tree ─────────────────────────────────────────────────────────────────
export const ANCIENT_TECH_TREE: TechNode[] = [
  // Tier 1
  {
    tech_id: 'ancient_iron_weapons',
    name: 'Iron Weapons',
    description: 'Superior metallurgy grants +1 attack die on all attack rolls.',
    tier: 1,
    cost: 4,
    attack_bonus: 1,
  },
  {
    tech_id: 'ancient_stone_walls',
    name: 'Stone Walls',
    description: 'Permanent fortifications — unlocks the defense_1 building.',
    tier: 1,
    cost: 4,
    unlocks_building: 'defense_1',
  },
  {
    tech_id: 'ancient_granaries',
    name: 'Granaries',
    description: 'Improved food storage — unlocks the production_1 building.',
    tier: 1,
    cost: 3,
    unlocks_building: 'production_1',
  },
  {
    tech_id: 'ancient_roads',
    name: 'Roman Roads',
    description: 'Extended road network grants +1 extra reinforcement per turn.',
    tier: 1,
    cost: 4,
    reinforce_bonus: 1,
  },
  // Tier 2
  {
    tech_id: 'ancient_siege_engines',
    name: 'Siege Engines',
    description: 'Catapults and ballistae: when attacking a territory with a defense building, ignore its bonus.',
    tier: 2,
    prerequisite: 'ancient_iron_weapons',
    cost: 7,
    attack_bonus: 1,
    unlocks_ability: 'siege_attack',
  },
  {
    tech_id: 'ancient_fortified_camps',
    name: 'Fortified Camps',
    description: 'Permanent legion camps — unlocks the defense_2 building.',
    tier: 2,
    prerequisite: 'ancient_stone_walls',
    cost: 7,
    unlocks_building: 'defense_2',
  },
  {
    tech_id: 'ancient_trade_routes',
    name: 'Trade Routes',
    description: 'Organized trade generates +1 tech point per owned territory per turn (capped 10).',
    tier: 2,
    prerequisite: 'ancient_granaries',
    cost: 6,
    tech_point_income: 3,
    unlocks_building: 'tech_gen_1',
  },
  {
    tech_id: 'ancient_cavalry',
    name: 'Cavalry',
    description: 'Mounted units allow one free re-fortify move per turn (units > 3 territory).',
    tier: 2,
    prerequisite: 'ancient_roads',
    cost: 6,
    reinforce_bonus: 1,
    unlocks_ability: 'cavalry_march',
  },
  // Tier 3
  {
    tech_id: 'ancient_legion_tactics',
    name: 'Legion Tactics',
    description: 'Advanced formation tactics: attacker re-rolls lowest die on ALL exchanges (stacks with legion_reroll era modifier).',
    tier: 3,
    prerequisite: 'ancient_siege_engines',
    cost: 11,
    attack_bonus: 1,
  },
  {
    tech_id: 'ancient_fortresses',
    name: 'Fortresses',
    description: 'Continental fortresses — unlocks the defense_3 building.',
    tier: 3,
    prerequisite: 'ancient_fortified_camps',
    cost: 11,
    unlocks_building: 'defense_3',
  },
  {
    tech_id: 'ancient_great_library',
    name: 'Great Library',
    description: 'Centre of learning — unlocks the tech_gen_2 building and grants +2 tech points per turn.',
    tier: 3,
    prerequisite: 'ancient_trade_routes',
    cost: 10,
    tech_point_income: 2,
    unlocks_building: 'tech_gen_2',
  },
  // Tier 4
  {
    tech_id: 'ancient_pax_romana',
    name: 'Pax Romana',
    description: 'Era of peace and prosperity: gain +3 reinforcements per turn and +1 tech point per owned region.',
    tier: 4,
    prerequisite: 'ancient_legion_tactics',
    cost: 16,
    reinforce_bonus: 3,
    tech_point_income: 2,
    unlocks_ability: 'pax_romana',
  },
];
