import type { Faction, TechNode } from './types';

// ── Factions ──────────────────────────────────────────────────────────────────
export const COLDWAR_FACTIONS: Faction[] = [
  {
    faction_id: 'usa_cw',
    name: 'United States',
    description: 'Global superpower — +1 tech point per ally-adjacent territory; influence ability range extended to 2 hops.',
    home_region_ids: ['north_america'],
    reinforce_bonus: 1,
    ability_id: 'marshall_plan',
    ability_description: 'Marshall Plan: once per turn during draft, place 1 free unit on any allied or newly captured territory.',
    color: '#3498db',
  },
  {
    faction_id: 'ussr',
    name: 'Soviet Union',
    description: 'Iron Curtain — influence ability can target territories within 2 hops; +1 defense die in Eastern Bloc territories.',
    home_region_ids: ['eastern_europe', 'central_asia'],
    passive_defense_bonus: 1,
    reinforce_bonus: 1,
    ability_id: 'iron_curtain',
    ability_description: 'Iron Curtain: once per turn, fortify up to 4 units to ANY owned territory regardless of path.',
    color: '#c0392b',
  },
  {
    faction_id: 'china_cw',
    name: "People's Republic of China",
    description: 'Vast army — +2 reinforcements per turn; guerrilla tactics grant +1 defense die in Asia.',
    home_region_ids: ['east_asia'],
    passive_defense_bonus: 1,
    reinforce_bonus: 2,
    ability_id: 'peoples_war',
    ability_description: "People's War: once per game, double your reinforcements for one turn.",
    color: '#e74c3c',
  },
  {
    faction_id: 'uk_cw',
    name: 'United Kingdom',
    description: 'Nuclear deterrent — if attacked in your capital territory, attacker loses 1 extra unit.',
    home_region_ids: ['western_europe'],
    passive_defense_bonus: 1,
    ability_id: 'nuclear_deterrence',
    ability_description: 'Nuclear Deterrence: once per game, cancel an attack against your capital territory entirely.',
    color: '#e67e22',
  },
  {
    faction_id: 'decolonization_movement',
    name: 'Non-Aligned Movement',
    description: 'Guerrilla movements challenge both superpowers — territories you own cannot be influenced (immune to influence_spread).',
    home_region_ids: ['africa', 'south_asia'],
    reinforce_bonus: 1,
    ability_id: 'guerrilla_resistance',
    ability_description: 'Guerrilla Resistance: once per turn, place 2 free units on any border territory that was attacked last turn.',
    color: '#27ae60',
  },
  {
    faction_id: 'nato_proxy',
    name: 'NATO Alliance',
    description: 'Collective defense pact — if any NATO territory is attacked, adjacent NATO territories each add +1 defense die.',
    home_region_ids: ['western_europe', 'mediterranean'],
    passive_defense_bonus: 1,
    ability_id: 'collective_defense',
    ability_description: 'Article 5: once per turn, an attack on any of your territories triggers +1 automatic defender loss on the attacker.',
    color: '#9b59b6',
  },
];

// ── Tech Tree ─────────────────────────────────────────────────────────────────
export const COLDWAR_TECH_TREE: TechNode[] = [
  // Tier 1
  {
    tech_id: 'cw_intelligence',
    name: 'Intelligence Agency',
    description: 'CIA/KGB ops — once per turn see enemy unit counts in fog-of-war territories adjacent to yours.',
    tier: 1,
    cost: 4,
    unlocks_ability: 'spy_network',
  },
  {
    tech_id: 'cw_bunker',
    name: 'Hardened Bunkers',
    description: 'Underground command — unlocks defense_1 building.',
    tier: 1,
    cost: 4,
    unlocks_building: 'defense_1',
  },
  {
    tech_id: 'cw_industry',
    name: 'Heavy Industry',
    description: 'Steel and coal production — unlocks production_1 building.',
    tier: 1,
    cost: 4,
    unlocks_building: 'production_1',
  },
  {
    tech_id: 'cw_propaganda',
    name: 'Propaganda Machine',
    description: 'Influence operations — your influence ability can now target 1 extra hop away.',
    tier: 1,
    cost: 5,
    unlocks_ability: 'propaganda_extended',
  },
  // Tier 2
  {
    tech_id: 'cw_jets',
    name: 'Jet Fighter Program',
    description: 'Air superiority — +1 attack die when attacking territories adjacent to your air-base territories.',
    tier: 2,
    prerequisite: 'cw_intelligence',
    cost: 9,
    attack_bonus: 1,
  },
  {
    tech_id: 'cw_fortified_zone',
    name: 'Fortified Zone',
    description: 'Militarized borders — unlocks defense_2 building.',
    tier: 2,
    prerequisite: 'cw_bunker',
    cost: 8,
    unlocks_building: 'defense_2',
  },
  {
    tech_id: 'cw_space_race',
    name: 'Space Race',
    description: 'Prestige and technology — unlocks tech_gen_1 building and +3 tech per turn.',
    tier: 2,
    prerequisite: 'cw_industry',
    cost: 8,
    tech_point_income: 3,
    unlocks_building: 'tech_gen_1',
  },
  {
    tech_id: 'cw_proxy_wars',
    name: 'Proxy Wars',
    description: 'Fund regime changes — influence ability now costs 2 units instead of 3.',
    tier: 2,
    prerequisite: 'cw_propaganda',
    cost: 7,
    unlocks_ability: 'proxy_funding',
  },
  // Tier 3
  {
    tech_id: 'cw_icbm',
    name: 'ICBM Program',
    description: 'Nuclear missiles — once per turn, reduce any territory\'s unit count by 2 without attacking.',
    tier: 3,
    prerequisite: 'cw_jets',
    cost: 14,
    unlocks_ability: 'nuclear_strike',
  },
  {
    tech_id: 'cw_missile_shield',
    name: 'Missile Defense Shield',
    description: 'ABM systems — unlocks defense_3 building; first attack each turn against your capital has -1 attacker die.',
    tier: 3,
    prerequisite: 'cw_fortified_zone',
    cost: 13,
    defense_bonus: 1,
    unlocks_building: 'defense_3',
  },
  {
    tech_id: 'cw_satellite',
    name: 'Satellite Network',
    description: 'Spy satellites — unlocks tech_gen_2 building and reveal all territories once per turn.',
    tier: 3,
    prerequisite: 'cw_space_race',
    cost: 12,
    tech_point_income: 2,
    unlocks_building: 'tech_gen_2',
    unlocks_ability: 'satellite_reconnaissance',
  },
  // Tier 4
  {
    tech_id: 'cw_detente',
    name: 'Détente',
    description: 'Diplomatic thaw — truce turns count as 0 cost; you can auto-influence any neutral territory within range.',
    tier: 4,
    prerequisite: 'cw_icbm',
    cost: 18,
    reinforce_bonus: 2,
    unlocks_ability: 'detente_protocol',
  },
];
