import type { Faction, TechNode } from './types';

// ── Factions ──────────────────────────────────────────────────────────────────
export const DISCOVERY_FACTIONS: Faction[] = [
  {
    faction_id: 'spain',
    name: 'Spanish Empire',
    description: 'Conquistadors press the advantage — +1 attack die when attacking territories in the Americas or Africa.',
    home_region_ids: ['iberia', 'mediterranean'],
    passive_attack_bonus: 1,
    ability_id: 'conquistador',
    ability_description: 'Conquistador: once per turn, capture a territory with 1 or 2 defenders without rolling dice (auto-capture, costs 2 of your units).',
    color: '#f39c12',
  },
  {
    faction_id: 'portugal',
    name: 'Portuguese Empire',
    description: 'Masters of the sea — sea_lanes connections allow 3 attack dice (normally 2) and free sea-lane fortify moves.',
    home_region_ids: ['iberia'],
    passive_attack_bonus: 1,
    ability_id: 'naval_charts',
    ability_description: 'Naval Charts: your sea_lanes attacks use the full 3 dice cap instead of the era-limited 2.',
    color: '#27ae60',
  },
  {
    faction_id: 'ottoman',
    name: 'Ottoman Empire',
    description: 'Straddling east and west — +2 reinforcements per turn from controlling the mediterranean sea_routes region.',
    home_region_ids: ['anatolia', 'middle_east'],
    reinforce_bonus: 2,
    ability_id: 'janissaries',
    ability_description: 'Janissaries: once per turn, defend with 3 dice regardless of garrison size.',
    color: '#d35400',
  },
  {
    faction_id: 'england_discovery',
    name: 'English Crown',
    description: 'Privateers and merchant adventurers — +1 tech point per sea territory owned.',
    home_region_ids: ['british_isles'],
    ability_id: 'privateer',
    ability_description: 'Privateer: once per turn, steal 1 production unit from an adjacent enemy coastal territory.',
    color: '#c0392b',
  },
  {
    faction_id: 'ming_china',
    name: 'Ming Dynasty',
    description: 'Vast population and the Great Wall — +1 defense die in Asian territories.',
    home_region_ids: ['east_asia'],
    passive_defense_bonus: 1,
    reinforce_bonus: 1,
    ability_id: 'great_wall',
    ability_description: "Great Wall: once per turn, prevent one attack from resolving (the attacker's turn is wasted).",
    color: '#e74c3c',
  },
  {
    faction_id: 'mughal',
    name: 'Mughal Empire',
    description: 'Rich subcontinent — generates +3 extra tech points per turn.',
    home_region_ids: ['south_asia'],
    ability_id: 'spice_trade',
    ability_description: 'Spice Trade: once per turn, exchange 5 tech points for 2 extra reinforcements.',
    color: '#9b59b6',
  },
];

// ── Tech Tree ─────────────────────────────────────────────────────────────────
export const DISCOVERY_TECH_TREE: TechNode[] = [
  // Tier 1
  {
    tech_id: 'discovery_cartography',
    name: 'Cartography',
    description: 'Better maps: sea_lanes attack uses full 3 dice (removes the 2-die cap from era modifier).',
    tier: 1,
    cost: 5,
    attack_bonus: 1,
  },
  {
    tech_id: 'discovery_fortifications',
    name: 'Star Forts',
    description: 'Bastion-trace fortification — unlocks defense_1 building.',
    tier: 1,
    cost: 4,
    unlocks_building: 'defense_1',
  },
  {
    tech_id: 'discovery_plantations',
    name: 'Colonial Plantations',
    description: 'Lucrative colonial agriculture — unlocks production_1 building.',
    tier: 1,
    cost: 3,
    unlocks_building: 'production_1',
  },
  {
    tech_id: 'discovery_muskets',
    name: 'Muskets',
    description: 'Matchlock firearms grant +1 attack die.',
    tier: 1,
    cost: 5,
    attack_bonus: 1,
  },
  // Tier 2
  {
    tech_id: 'discovery_galleons',
    name: 'Galleons',
    description: 'Warships allow 2 fortify moves along sea connections per turn.',
    tier: 2,
    prerequisite: 'discovery_cartography',
    cost: 8,
    reinforce_bonus: 1,
    unlocks_ability: 'galleon_transport',
  },
  {
    tech_id: 'discovery_citadel',
    name: 'Colonial Citadel',
    description: 'Reinforced fortifications — unlocks defense_2 building.',
    tier: 2,
    prerequisite: 'discovery_fortifications',
    cost: 7,
    unlocks_building: 'defense_2',
  },
  {
    tech_id: 'discovery_mercantilism',
    name: 'Mercantilism',
    description: 'State-directed commerce — unlocks tech_gen_1 building and +2 tech per turn.',
    tier: 2,
    prerequisite: 'discovery_plantations',
    cost: 6,
    tech_point_income: 2,
    unlocks_building: 'tech_gen_1',
  },
  {
    tech_id: 'discovery_artillery',
    name: 'Field Artillery',
    description: 'Cannon batteries add +1 attack die and negate defense building bonus.',
    tier: 2,
    prerequisite: 'discovery_muskets',
    cost: 8,
    attack_bonus: 1,
    unlocks_ability: 'artillery_barrage',
  },
  // Tier 3
  {
    tech_id: 'discovery_ironclads',
    name: 'Armored Galleons',
    description: 'Iron-plated warships — sea-lane attacks use full 3 dice and defender gets no sea bonus.',
    tier: 3,
    prerequisite: 'discovery_galleons',
    cost: 12,
    attack_bonus: 1,
  },
  {
    tech_id: 'discovery_fortress_network',
    name: 'Fortress Network',
    description: 'Coordinated fortresses — unlocks defense_3 building.',
    tier: 3,
    prerequisite: 'discovery_citadel',
    cost: 12,
    unlocks_building: 'defense_3',
  },
  {
    tech_id: 'discovery_stock_exchange',
    name: 'Stock Exchange',
    description: 'Amsterdam-style finance — unlocks tech_gen_2 and +3 tech points per turn.',
    tier: 3,
    prerequisite: 'discovery_mercantilism',
    cost: 11,
    tech_point_income: 3,
    unlocks_building: 'tech_gen_2',
  },
  // Tier 4
  {
    tech_id: 'discovery_empire',
    name: 'Global Empire',
    description: 'Colonies on every continent grant +3 reinforcements and +2 production per owned sea-adjacent territory.',
    tier: 4,
    prerequisite: 'discovery_ironclads',
    cost: 18,
    reinforce_bonus: 3,
    unlocks_ability: 'colonial_dominion',
  },
];
