import type { Faction, TechNode } from './types';

// ── Factions ──────────────────────────────────────────────────────────────────
export const MEDIEVAL_FACTIONS: Faction[] = [
  {
    faction_id: 'hre',
    name: 'Holy Roman Empire',
    description: 'Central European power — +1 defense die in mountainous territories and castle fortification era bonus.',
    home_region_ids: ['central_europe'],
    passive_defense_bonus: 1,
    reinforce_bonus: 1,
    ability_id: 'imperial_diet',
    ability_description: 'Imperial Diet: once per turn during draft, gain +2 extra reinforcements per fully owned region.',
    color: '#f39c12',
  },
  {
    faction_id: 'mongol_empire',
    name: 'Mongol Khanate',
    description: 'Devastating cavalry charges — +1 attack die on territories with fewer than 3 defenders.',
    home_region_ids: ['steppe_asia'],
    passive_attack_bonus: 1,
    ability_id: 'great_raid',
    ability_description: 'Great Raid: once per turn, attack a territory and move all (not just 3) units into captured territory.',
    color: '#d35400',
  },
  {
    faction_id: 'byzantine',
    name: 'Byzantine Empire',
    description: 'Sophisticated bureaucracy and Greek fire — +1 defense die in your capital region.',
    home_region_ids: ['byzantium'],
    passive_defense_bonus: 1,
    ability_id: 'greek_fire',
    ability_description: 'Greek Fire: once per turn, an attacking force loses 1 additional unit before dice are rolled.',
    color: '#8e44ad',
  },
  {
    faction_id: 'caliphate',
    name: 'Abbasid Caliphate',
    description: 'Intellectual hub and trade mastery — +2 tech points per turn passively.',
    home_region_ids: ['middle_east'],
    reinforce_bonus: 0,
    ability_id: 'house_of_wisdom',
    ability_description: 'House of Wisdom: once per turn, reduce the cost of a tech node by 3 (minimum 1).',
    color: '#16a085',
  },
  {
    faction_id: 'france',
    name: 'Kingdom of France',
    description: 'Chivalric knights — cavalry units grant +1 attack die when attacking from a territory you also hold a neighbor of.',
    home_region_ids: ['western_europe'],
    passive_attack_bonus: 1,
    ability_id: 'chevauchee',
    ability_description: 'Chevauchée: once per turn, raze an enemy territory (reduce unit count by 2) without attacking.',
    color: '#3498db',
  },
  {
    faction_id: 'england',
    name: 'Kingdom of England',
    description: 'Longbowmen add +1 attack die when attacking across a sea connection.',
    home_region_ids: ['british_isles'],
    passive_attack_bonus: 1,
    ability_id: 'longbowmen',
    ability_description: 'Longbowmen: once per turn, one ranged attack deals 1 unit loss to an adjacent enemy territory without a full attack exchange.',
    color: '#c0392b',
  },
];

// ── Tech Tree ─────────────────────────────────────────────────────────────────
export const MEDIEVAL_TECH_TREE: TechNode[] = [
  // Tier 1
  {
    tech_id: 'medieval_feudalism',
    name: 'Feudalism',
    description: 'Organized noble hierarchy — +1 reinforcement per turn.',
    tier: 1,
    cost: 4,
    reinforce_bonus: 1,
  },
  {
    tech_id: 'medieval_castle_keep',
    name: 'Castle Keep',
    description: 'Stout stone keeps — unlocks the defense_1 building (grants +1 defender die when garrisoned).',
    tier: 1,
    cost: 4,
    unlocks_building: 'defense_1',
  },
  {
    tech_id: 'medieval_guilds',
    name: 'Merchant Guilds',
    description: 'Urban commerce — unlocks production_1 building.',
    tier: 1,
    cost: 3,
    unlocks_building: 'production_1',
  },
  {
    tech_id: 'medieval_metallurgy',
    name: 'Advanced Metallurgy',
    description: 'Better plate armor for your defenders: +1 defense die.',
    tier: 1,
    cost: 4,
    defense_bonus: 1,
  },
  // Tier 2
  {
    tech_id: 'medieval_siege_warfare',
    name: 'Siege Warfare',
    description: 'Trebuchets and siege towers — castle_fortification defender bonus is negated when you attack.',
    tier: 2,
    prerequisite: 'medieval_metallurgy',
    cost: 8,
    attack_bonus: 1,
    unlocks_ability: 'siege_assault',
  },
  {
    tech_id: 'medieval_concentric_castle',
    name: 'Concentric Castle',
    description: 'Rings of walls — unlocks defense_2 building.',
    tier: 2,
    prerequisite: 'medieval_castle_keep',
    cost: 7,
    unlocks_building: 'defense_2',
  },
  {
    tech_id: 'medieval_banking',
    name: 'Banking System',
    description: 'Florentine banking networks — unlocks tech_gen_1 building and +2 tech points per turn.',
    tier: 2,
    prerequisite: 'medieval_guilds',
    cost: 6,
    tech_point_income: 2,
    unlocks_building: 'tech_gen_1',
  },
  {
    tech_id: 'medieval_chivalry',
    name: 'Chivalric Code',
    description: 'Elite knights — +1 attack die once per turn in one attack exchange.',
    tier: 2,
    prerequisite: 'medieval_feudalism',
    cost: 7,
    attack_bonus: 1,
    unlocks_ability: 'knights_charge',
  },
  // Tier 3
  {
    tech_id: 'medieval_gunpowder',
    name: 'Gunpowder',
    description: 'Early cannons add +1 die to all attacks. Negates enemy castle bonus.',
    tier: 3,
    prerequisite: 'medieval_siege_warfare',
    cost: 12,
    attack_bonus: 1,
    unlocks_ability: 'cannon_barrage',
  },
  {
    tech_id: 'medieval_citadel',
    name: 'Citadel',
    description: 'Impregnable city-fortress — unlocks defense_3 building.',
    tier: 3,
    prerequisite: 'medieval_concentric_castle',
    cost: 12,
    unlocks_building: 'defense_3',
  },
  {
    tech_id: 'medieval_renaissance',
    name: 'Early Renaissance',
    description: 'Cultural flourishing — unlocks tech_gen_2 building and +3 tech points per turn.',
    tier: 3,
    prerequisite: 'medieval_banking',
    cost: 11,
    tech_point_income: 3,
    unlocks_building: 'tech_gen_2',
  },
  // Tier 4
  {
    tech_id: 'medieval_dominion',
    name: 'Royal Dominion',
    description: 'Absolute monarchy consolidates power: +3 reinforcements per turn; castle_fortification is enhanced to grant 3 defense dice always.',
    tier: 4,
    prerequisite: 'medieval_gunpowder',
    cost: 17,
    reinforce_bonus: 3,
    unlocks_ability: 'royal_decree',
  },
];
