import type { Faction, TechNode } from './types';

// ── Factions ──────────────────────────────────────────────────────────────────
export const MODERN_FACTIONS: Faction[] = [
  {
    faction_id: 'western_power',
    name: 'Western Bloc',
    description: 'Precision warfare — precision_strike is always active; +1 defense die from advanced body armor.',
    home_region_ids: ['north_america', 'western_europe'],
    passive_defense_bonus: 1,
    passive_attack_bonus: 1,
    ability_id: 'precision_airstrike',
    ability_description: 'Precision Airstrike: once per turn, deal 2 unit losses to any adjacent enemy territory without a full attack exchange.',
    color: '#3498db',
  },
  {
    faction_id: 'eastern_bloc',
    name: 'Eastern Coalition',
    description: 'Armored mass — +2 reinforcements per turn; tanks let you move 2 extra units in fortify.',
    home_region_ids: ['eastern_europe', 'central_asia'],
    reinforce_bonus: 2,
    ability_id: 'armored_push',
    ability_description: 'Armored Push: once per turn, execute two fortify moves instead of one.',
    color: '#c0392b',
  },
  {
    faction_id: 'rogue_state',
    name: 'Rogue State',
    description: 'Asymmetric tactics — +1 defense die and immune to precision_strike attacker bonus.',
    home_region_ids: ['middle_east'],
    passive_defense_bonus: 2,
    ability_id: 'insurgency',
    ability_description: 'Insurgency: once per turn, spawn 1 free unit in a border territory that was attacked this turn.',
    color: '#e74c3c',
  },
  {
    faction_id: 'emerging_power',
    name: 'Emerging Economy',
    description: 'Rapid industrialization — earn 2 extra production units per turn from every territory with a production building.',
    home_region_ids: ['east_asia', 'south_asia'],
    reinforce_bonus: 1,
    ability_id: 'economic_boom',
    ability_description: 'Economic Boom: once per turn, pay 4 tech points to immediately place 2 units anywhere.',
    color: '#f39c12',
  },
  {
    faction_id: 'petro_state',
    name: 'Petrostate',
    description: 'Oil wealth — +3 tech points per turn; can buy an extra reinforcement for every 3 owned resource territories.',
    home_region_ids: ['middle_east', 'africa'],
    ability_id: 'oil_wealth',
    ability_description: 'Oil Wealth: once per turn, spend 6 tech points to place 3 extra units on any owned territory.',
    color: '#e67e22',
  },
  {
    faction_id: 'cyber_power',
    name: 'Cyber State',
    description: 'Digital warfare — once per turn, sabotage an adjacent enemy territory (remove 1 unit before combat).',
    home_region_ids: ['east_asia', 'north_america'],
    ability_id: 'cyber_attack',
    ability_description: 'Cyber Attack: once per turn, remove 1 unit from an adjacent enemy territory without combat.',
    color: '#9b59b6',
  },
];

// ── Tech Tree ─────────────────────────────────────────────────────────────────
export const MODERN_TECH_TREE: TechNode[] = [
  // Tier 1
  {
    tech_id: 'mod_drones',
    name: 'Drone Program',
    description: 'UAV reconnaissance — reveal all adjacent enemy territories each turn (ignores fog of war).',
    tier: 1,
    cost: 5,
    attack_bonus: 1,
    unlocks_ability: 'drone_recon',
  },
  {
    tech_id: 'mod_fortification',
    name: 'Military Bases',
    description: 'Permanent installations — unlocks defense_1 building.',
    tier: 1,
    cost: 4,
    unlocks_building: 'defense_1',
  },
  {
    tech_id: 'mod_economy',
    name: 'Digital Economy',
    description: 'Tech-driven growth — unlocks production_1 building.',
    tier: 1,
    cost: 4,
    unlocks_building: 'production_1',
  },
  {
    tech_id: 'mod_special_forces',
    name: 'Special Forces',
    description: 'Elite operators — precision_strike applies with 2 units (normally needs 4).',
    tier: 1,
    cost: 5,
    attack_bonus: 1,
    unlocks_ability: 'special_ops',
  },
  // Tier 2
  {
    tech_id: 'mod_stealth',
    name: 'Stealth Technology',
    description: 'Stealth aircraft — precision attacks cannot be countered; +1 attack die.',
    tier: 2,
    prerequisite: 'mod_drones',
    cost: 10,
    attack_bonus: 1,
  },
  {
    tech_id: 'mod_cyber_defense',
    name: 'Cyber Defense',
    description: 'Hardened networks — unlocks defense_2 building.',
    tier: 2,
    prerequisite: 'mod_fortification',
    cost: 8,
    unlocks_building: 'defense_2',
  },
  {
    tech_id: 'mod_ai_industry',
    name: 'AI-Driven Industry',
    description: 'Automated production — unlocks tech_gen_1 building and +2 tech per turn.',
    tier: 2,
    prerequisite: 'mod_economy',
    cost: 8,
    tech_point_income: 2,
    unlocks_building: 'tech_gen_1',
  },
  {
    tech_id: 'mod_hypersonic',
    name: 'Hypersonic Missiles',
    description: 'Long-range precision — once per turn, attack any adjacent territory that you could reach within 2 hops.',
    tier: 2,
    prerequisite: 'mod_special_forces',
    cost: 9,
    attack_bonus: 1,
    unlocks_ability: 'hypersonic_strike',
  },
  // Tier 3
  {
    tech_id: 'mod_space_weapons',
    name: 'Space-Based Weapons',
    description: 'Orbital strike platforms — once per turn, deal 3 unit losses to any enemy territory.',
    tier: 3,
    prerequisite: 'mod_stealth',
    cost: 15,
    unlocks_ability: 'orbital_strike',
  },
  {
    tech_id: 'mod_fortress',
    name: 'Fortress State',
    description: 'Comprehensive defense network — unlocks defense_3 building.',
    tier: 3,
    prerequisite: 'mod_cyber_defense',
    cost: 13,
    defense_bonus: 1,
    unlocks_building: 'defense_3',
  },
  {
    tech_id: 'mod_quantum',
    name: 'Quantum Computing',
    description: 'Quantum advantage — unlocks tech_gen_2 building and +4 tech per turn.',
    tier: 3,
    prerequisite: 'mod_ai_industry',
    cost: 13,
    tech_point_income: 4,
    unlocks_building: 'tech_gen_2',
  },
  // Tier 4
  {
    tech_id: 'mod_singularity',
    name: 'Technological Singularity',
    description: 'AI-controlled military — all attacks and defenses use maximum dice; +4 reinforcements per turn.',
    tier: 4,
    prerequisite: 'mod_space_weapons',
    cost: 22,
    attack_bonus: 2,
    defense_bonus: 1,
    reinforce_bonus: 4,
  },
];
