import type { Faction, TechNode } from './types';

// ── Factions ──────────────────────────────────────────────────────────────────
export const RISORGIMENTO_FACTIONS: Faction[] = [
  {
    faction_id: 'sardinia_piedmont',
    name: 'Kingdom of Sardinia',
    description: 'The catalyst of Italian unification — carbonari_network influence costs 1 fewer unit; +1 reinforce in Piedmont.',
    home_region_ids: ['piedmont', 'sardinia'],
    reinforce_bonus: 1,
    ability_id: 'unification_drive',
    ability_description: 'Unification Drive: once per turn, convert a neutral Italian territory within range at zero cost.',
    color: '#27ae60',
  },
  {
    faction_id: 'austria',
    name: 'Austrian Empire',
    description: 'Conservative power defending the old order — +2 defense dice in Austrian core territories.',
    home_region_ids: ['lombardy_venetia', 'austrian_core'],
    passive_defense_bonus: 2,
    reinforce_bonus: 1,
    ability_id: 'habsberg_garrison',
    ability_description: 'Habsburg Garrison: once per turn, immediately place 2 units in any Austrian-held territory under threat.',
    color: '#e74c3c',
  },
  {
    faction_id: 'papal_states',
    name: 'Papal States',
    description: 'Spiritual influence — carbonari_network range is halved against Papal territories; +1 defense die.',
    home_region_ids: ['papal_states'],
    passive_defense_bonus: 1,
    ability_id: 'papal_dispensation',
    ability_description: 'Papal Dispensation: once per turn, prevent one influence attempt against any Papal territory.',
    color: '#f1c40f',
  },
  {
    faction_id: 'kingdom_naples',
    name: 'Kingdom of the Two Sicilies',
    description: 'Southern stronghold — +1 defense die; Garibaldi attack bonus is negated in Neapolitan territory.',
    home_region_ids: ['naples', 'sicily'],
    passive_defense_bonus: 1,
    ability_id: 'bourbon_resistance',
    ability_description: 'Bourbon Resistance: once per game, prevent an enemy from capturing Sicily for one full turn.',
    color: '#d35400',
  },
];

// ── Tech Tree ─────────────────────────────────────────────────────────────────
export const RISORGIMENTO_TECH_TREE: TechNode[] = [
  // Tier 1
  {
    tech_id: 'riso_carbonari',
    name: 'Carbonari Networks',
    description: 'Secret societies extend influence reach by +1 hop.',
    tier: 1,
    cost: 3,
    unlocks_ability: 'expanded_network',
  },
  {
    tech_id: 'riso_fortifications',
    name: 'Field Fortifications',
    description: 'Modern earthworks — unlocks defense_1 building.',
    tier: 1,
    cost: 3,
    unlocks_building: 'defense_1',
  },
  {
    tech_id: 'riso_banking',
    name: 'Piedmontese Banking',
    description: 'Northern industrial finance — unlocks production_1 building.',
    tier: 1,
    cost: 3,
    unlocks_building: 'production_1',
  },
  {
    tech_id: 'riso_nationalism',
    name: 'Nationalist Sentiment',
    description: 'Rising nationalism — +1 reinforcement per turn for each fully owned region.',
    tier: 1,
    cost: 4,
    reinforce_bonus: 1,
  },
  // Tier 2
  {
    tech_id: 'riso_bersaglieri',
    name: 'Bersaglieri Corps',
    description: 'Elite light infantry — +1 attack die; rifle_doctrine re-rolls all tied dice.',
    tier: 2,
    prerequisite: 'riso_nationalism',
    cost: 7,
    attack_bonus: 1,
    unlocks_ability: 'bersaglieri_charge',
  },
  {
    tech_id: 'riso_walls',
    name: 'City Walls',
    description: 'Renaissance fortifications — unlocks defense_2 building.',
    tier: 2,
    prerequisite: 'riso_fortifications',
    cost: 6,
    unlocks_building: 'defense_2',
  },
  {
    tech_id: 'riso_trade',
    name: 'Mediterranean Trade',
    description: 'Sea commerce — unlocks tech_gen_1 building and +2 tech per turn.',
    tier: 2,
    prerequisite: 'riso_banking',
    cost: 5,
    tech_point_income: 2,
    unlocks_building: 'tech_gen_1',
  },
  {
    tech_id: 'riso_garibaldi',
    name: "Garibaldi's Redshirts",
    description: 'Volunteer revolutionary army — once per turn, execute a free influence on a neutral territory within 1 hop.',
    tier: 2,
    prerequisite: 'riso_carbonari',
    cost: 6,
    unlocks_ability: 'redshirts_march',
  },
  // Tier 3
  {
    tech_id: 'riso_artillery',
    name: 'Field Artillery',
    description: 'Modern cannon — negates enemy defense_1 building bonus.',
    tier: 3,
    prerequisite: 'riso_bersaglieri',
    cost: 10,
    attack_bonus: 1,
    unlocks_ability: 'artillery_support',
  },
  {
    tech_id: 'riso_citadel',
    name: 'Citadel',
    description: 'Impregnable fortress — unlocks defense_3 building.',
    tier: 3,
    prerequisite: 'riso_walls',
    cost: 10,
    unlocks_building: 'defense_3',
  },
  {
    tech_id: 'riso_unification',
    name: 'Proclamation of Unity',
    description: 'National consciousness — unlocks tech_gen_2 building and +3 tech per turn.',
    tier: 3,
    prerequisite: 'riso_trade',
    cost: 9,
    tech_point_income: 3,
    unlocks_building: 'tech_gen_2',
  },
  // Tier 4
  {
    tech_id: 'riso_kingdom_italy',
    name: 'Kingdom of Italy',
    description: 'Proclaimed unity — all Italian territories count as home region for reinforce bonus; +2 reinforcements per turn.',
    tier: 4,
    prerequisite: 'riso_artillery',
    cost: 14,
    reinforce_bonus: 2,
    unlocks_ability: 'risorgimento_complete',
  },
];
