import type { Faction, TechNode } from './types';

// ── Factions ──────────────────────────────────────────────────────────────────
export const WW2_FACTIONS: Faction[] = [
  {
    faction_id: 'germany',
    name: 'Third Reich',
    description: 'Blitzkrieg doctrine — after a successful capture, may make one immediate bonus attack per turn.',
    home_region_ids: ['western_europe', 'central_europe'],
    passive_attack_bonus: 1,
    ability_id: 'blitzkrieg',
    ability_description: 'Blitzkrieg: once per turn, after capturing a territory immediately execute a free additional attack from that territory.',
    color: '#7f8c8d',
  },
  {
    faction_id: 'soviet_union',
    name: 'Soviet Union',
    description: 'Vast reserves — +2 reinforcements per turn; wartime_logistics allows 3 fortify moves.',
    home_region_ids: ['eastern_europe', 'central_asia'],
    reinforce_bonus: 2,
    ability_id: 'mass_mobilization',
    ability_description: 'Mass Mobilization: once per game, place 5 extra units on any owned territory.',
    color: '#c0392b',
  },
  {
    faction_id: 'usa',
    name: 'United States',
    description: 'Industrial supremacy — +1 production unit from every owned territory per turn.',
    home_region_ids: ['north_america'],
    reinforce_bonus: 1,
    ability_id: 'arsenal_of_democracy',
    ability_description: 'Arsenal of Democracy: once per turn during draft, spend 5 production points to place 3 extra units.',
    color: '#3498db',
  },
  {
    faction_id: 'uk',
    name: 'United Kingdom',
    description: 'Island fortress and global empire — +1 defense die; sea-lane fortify is free.',
    home_region_ids: ['british_isles', 'africa'],
    passive_defense_bonus: 1,
    ability_id: 'commonwealth',
    ability_description: 'Commonwealth: once per turn, reinforce any owned territory from another owned territory via sea at no movement cost.',
    color: '#e74c3c',
  },
  {
    faction_id: 'japan',
    name: 'Imperial Japan',
    description: 'Pacific supremacy — sea-lane attacks use 3 dice; +1 attack die in Pacific or Asia regions.',
    home_region_ids: ['east_asia', 'southeast_asia'],
    passive_attack_bonus: 1,
    ability_id: 'banzai_charge',
    ability_description: 'Banzai Charge: once per turn, one attack exchange uses 4 attack dice (maximum).',
    color: '#e67e22',
  },
  {
    faction_id: 'china_ww2',
    name: 'Chinese Nationalists',
    description: 'Guerrilla resistance — +1 defense die; can spend production to place hidden reserve units.',
    home_region_ids: ['east_asia'],
    passive_defense_bonus: 1,
    ability_id: 'guerrilla_warfare',
    ability_description: 'Guerrilla Warfare: once per turn, place 1 unit on any owned territory for free.',
    color: '#27ae60',
  },
];

// ── Tech Tree ─────────────────────────────────────────────────────────────────
export const WW2_TECH_TREE: TechNode[] = [
  // Tier 1
  {
    tech_id: 'ww2_motorization',
    name: 'Motorization',
    description: 'Logistical vehicles — wartime_logistics grants 3 fortify moves (up from 2).',
    tier: 1,
    cost: 5,
    reinforce_bonus: 1,
    unlocks_ability: 'motorized_logistics',
  },
  {
    tech_id: 'ww2_bunkers',
    name: 'Bunker Network',
    description: 'Reinforced defensive positions — unlocks defense_1 building.',
    tier: 1,
    cost: 4,
    unlocks_building: 'defense_1',
  },
  {
    tech_id: 'ww2_war_industry',
    name: 'War Industry',
    description: 'Convert civilian industry to military production — unlocks production_1 building.',
    tier: 1,
    cost: 4,
    unlocks_building: 'production_1',
  },
  {
    tech_id: 'ww2_radio',
    name: 'Radio Communications',
    description: 'Coordinated troop movements — +1 reinforcement per turn.',
    tier: 1,
    cost: 3,
    reinforce_bonus: 1,
  },
  // Tier 2
  {
    tech_id: 'ww2_tanks',
    name: 'Tank Divisions',
    description: 'Armored spearheads — +1 attack die on all ground attacks.',
    tier: 2,
    prerequisite: 'ww2_motorization',
    cost: 9,
    attack_bonus: 1,
  },
  {
    tech_id: 'ww2_fortifications',
    name: 'Maginot-Line Fortifications',
    description: 'Deep defensive works — unlocks defense_2 building.',
    tier: 2,
    prerequisite: 'ww2_bunkers',
    cost: 8,
    unlocks_building: 'defense_2',
  },
  {
    tech_id: 'ww2_munitions',
    name: 'Mass Munitions',
    description: 'Industrial-scale weapons production — unlocks tech_gen_1 building and +2 tech per turn.',
    tier: 2,
    prerequisite: 'ww2_war_industry',
    cost: 7,
    tech_point_income: 2,
    unlocks_building: 'tech_gen_1',
  },
  {
    tech_id: 'ww2_air_support',
    name: 'Tactical Air Support',
    description: 'Coordinated artillery and airstrikes — one attack per turn deals 1 bonus damage before dice roll.',
    tier: 2,
    prerequisite: 'ww2_radio',
    cost: 8,
    unlocks_ability: 'air_strike',
  },
  // Tier 3
  {
    tech_id: 'ww2_panzer_tactics',
    name: 'Panzer Tactics',
    description: 'Armored penetration doctrine — blitzkrieg ability fires twice per turn.',
    tier: 3,
    prerequisite: 'ww2_tanks',
    cost: 13,
    attack_bonus: 1,
    unlocks_ability: 'double_blitz',
  },
  {
    tech_id: 'ww2_fortress_europe',
    name: 'Fortress Europe',
    description: 'Atlantic Wall-style defenses — unlocks defense_3 building.',
    tier: 3,
    prerequisite: 'ww2_fortifications',
    cost: 13,
    unlocks_building: 'defense_3',
  },
  {
    tech_id: 'ww2_radar',
    name: 'Radar Network',
    description: 'Early warning systems — unlocks tech_gen_2 building and +3 tech per turn.',
    tier: 3,
    prerequisite: 'ww2_munitions',
    cost: 11,
    tech_point_income: 3,
    unlocks_building: 'tech_gen_2',
  },
  // Tier 4
  {
    tech_id: 'ww2_atom_bomb',
    name: 'Manhattan Project',
    description: 'Ultimate weapon — once per game, instantly eliminate all units in one territory (leaves it neutral with 1 unit).',
    tier: 4,
    prerequisite: 'ww2_panzer_tactics',
    cost: 20,
    unlocks_ability: 'atom_bomb',
  },
];
